OPS_auto/urls.py
from django.urls import path

from . import views

app_name = 'OPS_auto'
urlpatterns=[
    path('', views.index, name='index'),
    ]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('', include('OPS_auto.urls')),
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns=[
    path('', views.homepage, name='homepage'),
    path('info', views.info, name='info'),
    ]

OPS_auto/models.py
from django.db import models

# Create your models here.

polls/models.py
import datetime
from django.db import models
from django.utils import timezone
# Create your models here.

class Question(models.Model):
    
    def __str__(self):
        return self.question_text
    
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('发布时间')


class Choice(models.Model):
    
    def __str__(self):
        return self.choice_text
    
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

OPS_auto/views.py
from django.shortcuts import render
from OPS_auto.scripts import getinfo
# Create your views here.

def index(request):
    t=getinfo.getMemCpu()
    title="hello"
    content = {"content":"新的一年，新的一天!","title":title}
    return render(request,'OPS_auto/index.html' ,content)

i = 1
count = 0
while 1:
    if i % 2 == 0 or i % 3 == 0:
        count += 1
        if count == 2333:
            print(i)
            break

    i += 1

polls/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.
from django.utils import timezone
from polls.scripts import getsum


def index(request):
    return HttpResponse("Hello, world. You're at the polls index.")

def info(request):
    user=request.POST["user"]
    try:
        users = getsum.sssum(int(user))
    except:
        users="不是合法内容"
    return HttpResponse(users)

def homepage(request):
    now=str(timezone.now())
    content={'now':now}
    return render(request,'polls/index.html' ,content)

OPS_auto/templates/OPS_auto/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- icon -->
    <link rel="icon" href="{% static 'production/images/favicon.ico' %}" type="image/x-icon" />
    <link rel="shortcut icon" href="{% static 'production/images/favicon.ico' %}" type="image/x-icon" />

    <title>开始吧! | </title>

    <!-- Bootstrap -->
    <link href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <!-- NProgress -->
    <link href="{% static 'nprogress/nprogress.css' %}" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="{% static 'build/css/custom.min.css' %}" rel="stylesheet">
    {% block headscript %}{% endblock %}
</head>

<body class="nav-md">
{% block container %}{% endblock %}
<!-- jQuery -->
<script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
<!-- Bootstrap -->
<script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
<!-- FastClick -->
<script src="{% static 'fastclick/lib/fastclick.js' %}"></script>
<!-- NProgress -->
<script src="{% static 'nprogress/nprogress.js' %}"></script>

<!-- Custom Theme Scripts -->
<script src="{% static 'build/js/custom.min.js' %}"></script>
{% block bodyscript %}{% endblock %}
</body>
</html>

OPS_auto/templates/OPS_auto/widget1.html
{% load staticfiles %}
<!-- start of weather widget -->
<div class="col-md-4 col-sm-6 col-xs-12">
  <div class="x_panel">
    <div class="x_title">
      <h2>Daily active users <small>Sessions</small></h2>
      <ul class="nav navbar-right panel_toolbox">
        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Settings 1</a>
            </li>
            <li><a href="#">Settings 2</a>
            </li>
          </ul>
        </li>
        <li><a class="close-link"><i class="fa fa-close"></i></a>
        </li>
      </ul>
      <div class="clearfix"></div>
    </div>
    <div class="x_content">
      <div class="row">
        <div class="col-sm-12">
          <div class="temperature"><b>Monday</b>, 07:30 AM
            <span>F</span>
            <span><b>C</b></span>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-4">
          <div class="weather-icon">
            <canvas height="84" width="84" id="partly-cloudy-day"></canvas>
          </div>
        </div>
        <div class="col-sm-8">
          <div class="weather-text">
            <h2>Texas <br><i>Partly Cloudy Day</i></h2>
          </div>
        </div>
      </div>
      <div class="col-sm-12">
        <div class="weather-text pull-right">
          <h3 class="degrees">23</h3>
        </div>
      </div>

      <div class="clearfix"></div>

      <div class="row weather-days">
        <div class="col-sm-2">
          <div class="daily-weather">
            <h2 class="day">Mon</h2>
            <h3 class="degrees">25</h3>
            <canvas id="clear-day" width="32" height="32"></canvas>
            <h5>15 <i>km/h</i></h5>
          </div>
        </div>
        <div class="col-sm-2">
          <div class="daily-weather">
            <h2 class="day">Tue</h2>
            <h3 class="degrees">25</h3>
            <canvas height="32" width="32" id="rain"></canvas>
            <h5>12 <i>km/h</i></h5>
          </div>
        </div>
        <div class="col-sm-2">
          <div class="daily-weather">
            <h2 class="day">Wed</h2>
            <h3 class="degrees">27</h3>
            <canvas height="32" width="32" id="snow"></canvas>
            <h5>14 <i>km/h</i></h5>
          </div>
        </div>
        <div class="col-sm-2">
          <div class="daily-weather">
            <h2 class="day">Thu</h2>
            <h3 class="degrees">28</h3>
            <canvas height="32" width="32" id="fog"></canvas>
            <h5>15 <i>km/h</i></h5>
          </div>
        </div>
        <div class="col-sm-2">
          <div class="daily-weather">
            <h2 class="day">Fri</h2>
            <h3 class="degrees">28</h3>
            <canvas height="32" width="32" id="wind"></canvas>
            <h5>11 <i>km/h</i></h5>
          </div>
        </div>
        <div class="col-sm-2">
          <div class="daily-weather">
            <h2 class="day">Sat</h2>
            <h3 class="degrees">26</h3>
            <canvas height="32" width="32" id="cloudy"></canvas>
            <h5>10 <i>km/h</i></h5>
          </div>
        </div>
        <div class="clearfix"></div>
      </div>
    </div>
  </div>
</div>
{% block bodyscript %}
<script src="{% static 'skycons/skycons.js' %}"></script>
{% endblock %}

polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ now }}</title>
</head>
<body>
<form name="input" action="{% url 'polls:info' %}" method="post">
    {% csrf_token %}
请输入: <input type="text" name="user">
<input type="submit" value="提交">
</form>
</body>
</html>